%----------------------------------------------------------------------------------------
%	BIBLIOGRAPHY
%----------------------------------------------------------------------------------------
\newcommand{\sidecite}[2][0pt]{\sidenote[][#1]{\textcite{#2}}} % Parenthetical citations in the margin
\newcommand{\fullsidecite}[2][0pt]{\sidenote[][#1]{\fullcite{#2}}} % Full citations in the margin
