%----------------------------------------------------------------------------------------
%	LINKS
%----------------------------------------------------------------------------------------

\usepackage{hyperref} % Required for links

\hypersetup{
%	colorlinks=true, % Whether to color the text of links
	linkcolor=blueal, % Color for \nameref links
%	pdfborderstyle={/S/U/W 1}, % Style for the box (U for underline, W for border width)
	linkbordercolor=blueal,   % Color of the box
}